config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'app/posts#index'

  namespace :admin do
    resources :posts
    get 'admin_post/(:id)', :to => 'posts#admin_post'
    post 'create_or_update/:current_user/(:id)', :to => 'posts#create_or_update'
  end

  namespace :app do
    resources :posts
    get 'archive', :to => 'posts#archive'
  end

  devise_for :users, controllers: {
       sessions: 'admin/sessions',
       skip: :registrations
  }

  get 'admin', :to => 'admin/posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image
  validates :title, :content, :image, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :user_id, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, authentication_keys: [:user_id]

  has_many :posts
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  prepend_before_action :authenticate_user!

  def index
    @user = current_user.id
    @posts = Post.all
  end

  def admin_post
    @user = current_user.id
    if params[:id] != nil
      @post = Post.find(params[:id])
    end
  end

  def create_or_update
    if params[:id] != nil
      @post = Post.find(params[:id])
      @post.update_attributes(:title => params[:title], :content => params[:inquiry])

      if(params[:image] != nil)
        @post.update_attributes(:image => params[:image])
      end

      if @post.save()
        redirect_to admin_posts_path()
      else
        redirect_to request.referrer, error: 'Article is successfully created'
      end

    else
      @post = Post.new(:title=>params[:title], :image=>params[:image], :content=>params[:inquiry], :users_id => params[:current_user])
      if @post.save
        redirect_to admin_posts_path(), notice: "OMG IT'S WORKING"
      else
      end
    end
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  protect_from_forgery with: :null_session
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/app/posts_controller.rb
class App::PostsController < ApplicationController
  def index
    @posts = Post.limit(5)
  end

  def show
    @post = Post.find(params[:id])
  end

  def archive
    @posts = Post.paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  add_flash_types :success, :error

  def after_sign_in_path_for(resource)
    admin_posts_path
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/app/posts_helper.rb
module App::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_rederer
    Class.new(WillPaginate::ActionView::LinkRenderer) do
      def container_attributes
        {class: "paginate"}
      end

      def page_number(page)
        if page == current_page
          tag(:span, page, class: 'paginate-number is-current')
        else
          link(page, page, class: 'paginate-number', rel: rel_value(page))
        end
      end

      def gap
        text = @template.will_paginate_translate(:page_gap) { '&hellip;' }
        %(<span class="mr2">#{text}</span>)
      end

      def previous_page
        num = @collection.current_page > 1 && @collection.current_page - 1
        previous_or_next_page(num, 'paginate-prev')
      end

      def next_page
        num = @collection.current_page < total_pages && @collection.current_page + 1
        previous_or_next_page(num, 'paginate-next')
      end

      def previous_or_next_page(page, classname)
        arrow = ''
        if classname == 'paginate-next'
          arrow = '%(<span class="paginate-next-arrow"></span>)'
        else
          arrow = '%(<span class="paginate-prev-arrow"></span>)'
        end

        if page
          link(arrow ,page, :class => classname)
        else
          tag(:span, arrow , :class => classname + ' is-disable')
        end
      end
    end
  end
end

app/views/admin/posts/_admin_list.html.erb
<ul class="archive archive-admin">
  <% @posts.each do |post| %>
    <li class="archive-item">
      <%= link_to admin_path(post.id), :class=> "post-article" do %>
        <time class="post-article-date"><%= post.created_at.strftime("%d %b, %Y")%></time>
        <h1 class="post-article-title"><%= post.title%></h1>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/admin/posts/_footer.html.erb
<footer class="l-footer ">
  <div class="l-footer-copyright">
    <small class="copyright">&copy;copyright</small>
  </div>
</footer>

app/views/admin/posts/_header.html.erb
<header class="l-header l-header-admin js-header">
  <div class="l-header-top u-clear">
    <div class="l-header-logo">
      <a class="logo " href="./">
        <img src="/assets/logo-admin.png" width="138" height="28" alt="BLOG"/>
      </a>
    </div>
    <div class="l-header-text">
      <p>ADMIN PAGE</p>
    </div>
  </div>
</header>

app/views/admin/posts/admin_post.html.erb
<%= render './top' %>

<div class="l-wrap js-wrap">
  <!--start header-->
  <%= render 'header' %>
  <!--end header-->
  <!--start l-contents-->
  <div class="l-container u-clear">
    <!--start l-main-->
    <main class="l-main js-main">
      <div class="l-main-block"></div>
      <form name="user_form" action="/admin/create_or_update/<%= @user%>/<%= @post && @post.id  %>"
        onsubmit="return validateForm()" class="form" method="post" enctype="multipart/form-data">
        <label for="image" class="form-title">EYE CATCH IMAGE
          <div class="form-file u-clear">
              <span class="form-file-button">UPLOAD</span>
              <input type="file" id="image" class="input input-image" name="image">
              <div id="filename"><%= @post && @post.image.original_filename %></div>
          </div>
        </label>

        <label for="title" class="form-title">TITLE</label>
        <div class="form-body">
            <input type="text" id="title" class="input input-text" name="title"
              value="<%= @post && @post.title %>">
        </div>
        <label for="contents" class="form-title">CONTENTS</label>
        <div class="form-textarea">
            <textarea name="inquiry" id="inquiry" cols="30" rows="10" class="input input-contents"><%= @post && @post.content %></textarea>
        </div>

        <p id="error"></p >

        <label for="submit" class="form-button">
        <div class="button">
          <p class="button-text">Submit</p>
        </div>
        </label>
        <input type="submit" id="submit" class="input input-submit">
        <a href="<%= admin_posts_path %>" class="form-button">
            <div class="button">
              <p class="button-text">Back</p>
            </div>
        </a>
      </form>
    </main>
    <!--end l-main-->
  </div>
  <!--end l-contents-->
  <!--footer ここから-->
  <%= render 'footer' %>
  <!--footer ここまで-->
</div>

app/views/admin/posts/index.html.erb
<%= render './top' %>

<div class="l-wrap js-wrap">
  <!--start header-->
  <%= render 'header' %>
  <!--end header-->
  <!--start l-contents-->
  <div class="l-container u-clear">
    <!--start l-main-->
    <main class="l-main js-main">
      <div class="l-main-block"></div>
      <a href="<%= admin_path %>" class="l-main-button">
        <div class="button">
          <p class="button-text">New Article</p>
        </div>
      </a>
      <%= render 'admin_list' %>
    </main>
    <!--end l-main-->
  </div>

  <!--end l-contents-->
  <!--footer ここから-->
  <%= render 'footer' %>
  <!--footer ここまで-->
</div>

app/views/app/posts/_archive_list.html.erb
<div class="archive">
  <ul class="archive-list">
    <% @posts.each do |post| %>
      <li class="archive-item">
        <article class="card">
          <%= link_to app_post_path(post.id) do%>
            <%= image_tag post.image.url(), :class =>"card-image"%>
            <div class="card-bottom">
              <h1 class="card-title"><%= post.title%></h1>
              <time class="card-date" >
                <%= post.created_at.strftime("%d %b, %Y") %>
              </time>
            </div>
          <% end %>
        </article>
      </li>
    <% end %>
  </ul>
</div>

app/views/app/posts/_footer.html.erb
<footer class="l-footer ">
  <div class="l-footer-button">
    <a class="page-top js-scroll" href="#js-body">
      <span class="page-top-arrow"></span>
    </a>
  </div>
  <div class="l-footer-copyright">
    <small class="copyright">&copy;copyright</small>
  </div>
</footer>

app/views/app/posts/_hamburger.html.erb
<div class="l-header-hamburger">
  <a href="#" class="hamburger js-hamburger " >
    <span class="hamburger-item"></span>
    <span class="hamburger-item"></span>
    <span class="hamburger-item"></span>
  </a>
</div>

app/views/app/posts/_header.html.erb
<header class="l-header  js-header">
  <div class="l-header-top u-clear">

    <div class="l-header-logo">
      <div class="logo">
        <a class="logo " href="<%= locals[:route] %>">
          <img src="/assets/logo.png" width="253" height="28" alt="BLOG"/>
        </a>
      </div>
    </div>
    <%= render 'hamburger' %>
  </div>
</header>
<!--end header-->
<nav class="nav js-nav">
  <ul class="nav-list">
    <li class="nav-item">
      <a href="<%= root_path %>" class="nav-link">TOP</a>
    </li>
    <li class="nav-item">
      <a href="https://www.facebook.com/facebook/" class="nav-link">Facebook</a>
    </li>
    <li class="nav-item">
      <a href="https://twitter.com/twitter" class="nav-link">Twitter</a>
    </li>
  </ul>
</nav>

app/views/app/posts/archive.html.erb
<%= render './top' %>

<div class="l-wrap js-wrap">
  <!--start header-->
  <%= render 'header', :locals => {:route => ''} %>
  <!--end header-->
  <!--start l-contents-->
  <div class="l-container u-clear">
    <!--start l-main-->
    <main class="l-main js-main">
      <div class="l-main-block"></div>
      <div class="page-number">
        Page <span> <%= @posts.current_page %>/<%= @posts.total_pages %></span>
      </div>
      <%= render 'archive_list' %>
      <%= will_paginate @posts, renderer: custom_rederer, inner_window: 1, outer_window: 0%>
    </main>
    <!--end l-main-->
  </div>
</div>
<!--end l-contents-->

<!--footer ここから-->
<%= render 'footer' %>
<!--footer ここまで-->

app/views/app/posts/index.html.erb
<%= render './top' %>
<div class="l-wrap js-wrap">
  <!--start header-->
  <%= render 'header', :locals => {:route => root_path} %>
  <!--start l-contents-->
  <div class="l-container u-clear">
  <!--start l-main-->
    <main class="l-main js-main">
      <div class="l-main-block"></div>
      <%= render 'archive_list' %>
      <a href="<%= app_archive_path %>" class="archive-button">
          <div class="button">
            <p class="button-text">More</p>
          </div>
      </a>
    </main>
  <!--end l-main-->
  </div>
  <!--end l-contents-->
  <!--footer ここから-->
  <%= render 'footer' %>
    <!--footer ここまで-->
</div>

app/views/app/posts/show.html.erb
<%= render './top' %>

<div class="l-wrap js-wrap">
  <!--start header-->
  <%= render 'header', :locals => {:route => ''} %>
  <!--end header-->
  <!--start l-main-->
  <main class="l-main js-main">
    <div class="l-main-block"></div>
    <div class="single">
      <%= image_tag @post.image.url(), :class =>"single-image"%>
      <div class="l-container u-clear">
        <h1 class="single-title"><%= @post.title %></h1>
        <time class="single-date" datetime="2016-9-16"><%= @post.created_at.strftime("%d %b, %Y") %></time>
        <p class="single-desc"><%= @post.content %></p>
        <div class="single-button">
          <div class="button">
            <%= link_to root_path do%>
              <p class="button-text">Top</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </main>
  <!--end l-main-->

  <!--footer ここから-->
  <%= render 'footer' %>
  <!--footer ここまで-->
</di  v>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 9]>
<html lang="ja" class="no-js lt-ie9" prefix="og: http://ogp.me/ns#">
<![endif]-->
<!--[if gt IE 9]><!-->
<html lang="ja" class="no-js" prefix="og: http://ogp.me/ns#"><!--<![endif]-->
  <head>
    <title>Blog</title>
    <meta charset="UTF-8">
    <meta name="description" content="sample text,sample tex">
    <meta name="keywords" content="word1,word2,word3">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta property="og:title" content="">
    <meta property="og:description" content="sample text,sample tex">
    <meta property="og:url" content="">
    <meta property="og:site_name" content="">
    <meta property="og:type" content="blog">
    <meta property="fb:admins" content="">
    <meta property="og:image" content="/assets/common/ogp.png">

    <meta name="apple-mobile-web-app-title" content="">

    <link rel="shortcut icon" href="/assets/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-precomposed.png">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="js-body">
    <%= yield %>
    <script src="/assets/jquery-3.1.1.min.js"></script>
    <script src="/assets/app.js"></script>
  </body id="js-body">
</html>